<a href="https://colab.research.google.com/github/lakkireddylahari-bot/data-science-learning/blob/main/encoder1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# encoder is the process of converting the categorical data into numerical data
# these are two tyes
# LabelEncoder
# one hot encoder
# label encoder converts the category into a unique number

[10 20 30 40 50 60]
35.0
60
10
210
50.0

In [ ]:
# scikit is an open source python language used for machine learning tasks such as
#  data preprocessing , model building, model training,evaluation
from sklearn.preprocessing import LabelEncoder
import seaborn as sns
df = sns.load_dataset("tips")

In [ ]:
df

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [ ]:
sex_data = df["sex"]

In [ ]:
encoder = LabelEncoder()
encoded = encoder.fit_transform(sex_data)
print(encoded)

[0 1 1 1 0 1 1 1 1 1 1 0 1 1 0 1 0 1 0 1 1 0 0 1 1 1 1 1 1 0 1 1 0 0 1 1 1
 0 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 1 1 1 1 0 1 1 1 1 1 1 1 1 0 0 1 1 1 0 0 0
 0 1 1 1 1 1 1 1 0 1 1 0 1 1 1 1 1 1 0 0 0 1 1 1 1 1 0 0 0 0 0 1 1 1 1 0 1
 0 1 1 0 0 1 0 0 0 1 0 1 1 0 0 1 0 0 1 1 0 0 0 0 0 0 0 1 0 0 1 1 0 0 0 0 0
 1 1 1 1 1 1 1 0 1 0 0 1 1 1 0 1 0 1 1 1 0 0 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1
 1 0 1 0 1 1 0 1 1 1 1 1 0 0 1 1 0 0 0 1 0 1 1 1 0 1 1 1 0 0 0 1 1 1 0 1 0
 1 0 1 0 0 1 1 0 1 1 1 1 1 1 1 1 0 1 0 1 1 0]

In [ ]:
df["sex"] = encoded

In [ ]:
df

     total_bill   tip  sex smoker   day    time  size
0         16.99  1.01    0     No   Sun  Dinner     2
1         10.34  1.66    1     No   Sun  Dinner     3
2         21.01  3.50    1     No   Sun  Dinner     3
3         23.68  3.31    1     No   Sun  Dinner     2
4         24.59  3.61    0     No   Sun  Dinner     4
..          ...   ...  ...    ...   ...     ...   ...
239       29.03  5.92    1     No   Sat  Dinner     3
240       27.18  2.00    0    Yes   Sat  Dinner     2
241       22.67  2.00    1    Yes   Sat  Dinner     2
242       17.82  1.75    1     No   Sat  Dinner     2
243       18.78  3.00    0     No  Thur  Dinner     2

[244 rows x 7 columns]

In [ ]:
import seaborn as sns
df = sns.load_dataset("titanic")

In [ ]:
print(df.head())

   survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third
1         1       1  female  38.0      1      0  71.2833        C  First
2         1       3  female  26.0      0      0   7.9250        S  Third
3         1       1  female  35.0      1      0  53.1000        S  First
4         0       3    male  35.0      0      0   8.0500        S  Third

     who  adult_male deck  embark_town alive  alone
0    man        True  NaN  Southampton    no  False
1  woman       False    C    Cherbourg   yes  False
2  woman       False  NaN  Southampton   yes   True
3  woman       False    C  Southampton   yes  False
4    man        True  NaN  Southampton    no   True

In [ ]:
df.columns

Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town',
       'alive', 'alone'],
      dtype='object')

In [ ]:
encoder = LabelEncoder()
encoded = encoder.fit_transform(sex_data)
print(encoded)

[0 1 1 1 0 1 1 1 1 1 1 0 1 1 0 1 0 1 0 1 1 0 0 1 1 1 1 1 1 0 1 1 0 0 1 1 1
 0 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 1 1 1 1 0 1 1 1 1 1 1 1 1 0 0 1 1 1 0 0 0
 0 1 1 1 1 1 1 1 0 1 1 0 1 1 1 1 1 1 0 0 0 1 1 1 1 1 0 0 0 0 0 1 1 1 1 0 1
 0 1 1 0 0 1 0 0 0 1 0 1 1 0 0 1 0 0 1 1 0 0 0 0 0 0 0 1 0 0 1 1 0 0 0 0 0
 1 1 1 1 1 1 1 0 1 0 0 1 1 1 0 1 0 1 1 1 0 0 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1
 1 0 1 0 1 1 0 1 1 1 1 1 0 0 1 1 0 0 0 1 0 1 1 1 0 1 1 1 0 0 0 1 1 1 0 1 0
 1 0 1 0 0 1 1 0 1 1 1 1 1 1 1 1 0 1 0 1 1 0]

In [ ]:
from sklearn.preprocessing import LabelEncoder

sex_data = df["sex"]
encoder = LabelEncoder()
encoded = encoder.fit_transform(sex_data)
df["sex"] = encoded

In [ ]:
df

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,1,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,0,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,0,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,0,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,1,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,1,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,0,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,0,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,1,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,1,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [ ]:
display(df.head(10))

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,1,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,0,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,0,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,0,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,1,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
5,0,3,1,NaN,0,0,8.4583,Q,Third,man,True,NaN,Queenstown,no,True
6,0,1,1,54.0,0,0,51.8625,S,First,man,True,E,Southampton,no,True
7,0,3,1,2.0,3,1,21.0750,S,Third,child,False,NaN,Southampton,no,False
8,1,3,0,27.0,0,2,11.1333,S,Third,woman,False,NaN,Southampton,yes,False
9,1,2,0,14.0,1,0,30.0708,C,Second,child,False,NaN,Cherbourg,yes,False

In [ ]:
import seaborn as sns
# Reload the titanic dataset as it was overwritten by the tips dataset
df = sns.load_dataset("titanic")

class_column = df['class']
from sklearn.preprocessing import LabelEncoder

class_data = df["class"]
encoder = LabelEncoder()
encoded = encoder.fit_transform(class_data)
df["class"] = encoded

In [ ]:
df

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,1,22.0,1,0,7.2500,S,2,man,True,NaN,Southampton,no,False
1,1,1,0,38.0,1,0,71.2833,C,0,woman,False,C,Cherbourg,yes,False
2,1,3,0,26.0,0,0,7.9250,S,2,woman,False,NaN,Southampton,yes,True
3,1,1,0,35.0,1,0,53.1000,S,0,woman,False,C,Southampton,yes,False
4,0,3,1,35.0,0,0,8.0500,S,2,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,1,27.0,0,0,13.0000,S,1,man,True,NaN,Southampton,no,True
887,1,1,0,19.0,0,0,30.0000,S,0,woman,False,B,Southampton,yes,True
888,0,3,0,NaN,1,2,23.4500,S,2,woman,False,NaN,Southampton,no,False
889,1,1,1,26.0,0,0,30.0000,C,0,man,True,C,Cherbourg,yes,True
890,0,3,1,32.0,0,0,7.7500,Q,2,man,True,NaN,Queenstown,no,True

In [ ]:
display(df.head(10))

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,1,22.0,1,0,7.2500,S,2,man,True,NaN,Southampton,no,False
1,1,1,0,38.0,1,0,71.2833,C,0,woman,False,C,Cherbourg,yes,False
2,1,3,0,26.0,0,0,7.9250,S,2,woman,False,NaN,Southampton,yes,True
3,1,1,0,35.0,1,0,53.1000,S,0,woman,False,C,Southampton,yes,False
4,0,3,1,35.0,0,0,8.0500,S,2,man,True,NaN,Southampton,no,True
5,0,3,1,NaN,0,0,8.4583,Q,2,man,True,NaN,Queenstown,no,True
6,0,1,1,54.0,0,0,51.8625,S,0,man,True,E,Southampton,no,True
7,0,3,1,2.0,3,1,21.0750,S,2,child,False,NaN,Southampton,no,False
8,1,3,0,27.0,0,2,11.1333,S,2,woman,False,NaN,Southampton,yes,False
9,1,2,0,14.0,1,0,30.0708,C,1,child,False,NaN,Cherbourg,yes,False

In [ ]:
from sklearn.preprocessing import LabelEncoder

embarked_data = df["embarked"]
encoder = LabelEncoder()
encoded = encoder.fit_transform(embarked_data)
df["embarked"] = encoded

In [ ]:
df

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,1,22.0,1,0,7.2500,2,2,man,True,NaN,Southampton,no,False
1,1,1,0,38.0,1,0,71.2833,0,0,woman,False,C,Cherbourg,yes,False
2,1,3,0,26.0,0,0,7.9250,2,2,woman,False,NaN,Southampton,yes,True
3,1,1,0,35.0,1,0,53.1000,2,0,woman,False,C,Southampton,yes,False
4,0,3,1,35.0,0,0,8.0500,2,2,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,1,27.0,0,0,13.0000,2,1,man,True,NaN,Southampton,no,True
887,1,1,0,19.0,0,0,30.0000,2,0,woman,False,B,Southampton,yes,True
888,0,3,0,NaN,1,2,23.4500,2,2,woman,False,NaN,Southampton,no,False
889,1,1,1,26.0,0,0,30.0000,0,0,man,True,C,Cherbourg,yes,True
890,0,3,1,32.0,0,0,7.7500,1,2,man,True,NaN,Queenstown,no,True

In [ ]:
display(df.head(10))

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,1,22.0,1,0,7.2500,2,2,man,True,NaN,Southampton,no,False
1,1,1,0,38.0,1,0,71.2833,0,0,woman,False,C,Cherbourg,yes,False
2,1,3,0,26.0,0,0,7.9250,2,2,woman,False,NaN,Southampton,yes,True
3,1,1,0,35.0,1,0,53.1000,2,0,woman,False,C,Southampton,yes,False
4,0,3,1,35.0,0,0,8.0500,2,2,man,True,NaN,Southampton,no,True
5,0,3,1,NaN,0,0,8.4583,1,2,man,True,NaN,Queenstown,no,True
6,0,1,1,54.0,0,0,51.8625,2,0,man,True,E,Southampton,no,True
7,0,3,1,2.0,3,1,21.0750,2,2,child,False,NaN,Southampton,no,False
8,1,3,0,27.0,0,2,11.1333,2,2,woman,False,NaN,Southampton,yes,False
9,1,2,0,14.0,1,0,30.0708,0,1,child,False,NaN,Cherbourg,yes,False

In [ ]:

# one hot encoder
# it is a technique used to
# convert text data into numerical data by creating seperate columns for each
# category and filling thems with 0s and 1s
import seaborn as sns
from sklearn.preprocessing import OneHotEncoder
df = sns.load_dataset("tips")

In [ ]:
df

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [ ]:
sex_data = df[["sex"]] # Pass a DataFrame with a single column
encoder = OneHotEncoder(sparse_output = False)
encoded = encoder.fit_transform(sex_data)
print(encoded)

[[1. 0.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [1. 0.]]

In [ ]:
print(encoder.get_feature_names_out())

['sex_Female' 'sex_Male']

In [ ]:
import pandas as pd

In [ ]:
encoded_df = pd.DataFrame(
    encoded,
    columns = encoder.get_feature_names_out()
)
encoded_df

     sex_Female  sex_Male
0           1.0       0.0
1           0.0       1.0
2           0.0       1.0
3           0.0       1.0
4           1.0       0.0
..          ...       ...
239         0.0       1.0
240         1.0       0.0
241         0.0       1.0
242         0.0       1.0
243         1.0       0.0

[244 rows x 2 columns]

In [ ]:
d = df.drop("sex", axis = 1)

In [ ]:
d

     total_bill   tip smoker   day    time  size
0         16.99  1.01     No   Sun  Dinner     2
1         10.34  1.66     No   Sun  Dinner     3
2         21.01  3.50     No   Sun  Dinner     3
3         23.68  3.31     No   Sun  Dinner     2
4         24.59  3.61     No   Sun  Dinner     4
..          ...   ...    ...   ...     ...   ...
239       29.03  5.92     No   Sat  Dinner     3
240       27.18  2.00    Yes   Sat  Dinner     2
241       22.67  2.00    Yes   Sat  Dinner     2
242       17.82  1.75     No   Sat  Dinner     2
243       18.78  3.00     No  Thur  Dinner     2

[244 rows x 6 columns]

In [ ]:
final_df = pd.concat([d,encoded_df], axis = 1)
final_df

     total_bill   tip smoker   day    time  size  sex_Female  sex_Male
0         16.99  1.01     No   Sun  Dinner     2         1.0       0.0
1         10.34  1.66     No   Sun  Dinner     3         0.0       1.0
2         21.01  3.50     No   Sun  Dinner     3         0.0       1.0
3         23.68  3.31     No   Sun  Dinner     2         0.0       1.0
4         24.59  3.61     No   Sun  Dinner     4         1.0       0.0
..          ...   ...    ...   ...     ...   ...         ...       ...
239       29.03  5.92     No   Sat  Dinner     3         0.0       1.0
240       27.18  2.00    Yes   Sat  Dinner     2         1.0       0.0
241       22.67  2.00    Yes   Sat  Dinner     2         0.0       1.0
242       17.82  1.75     No   Sat  Dinner     2         0.0       1.0
243       18.78  3.00     No  Thur  Dinner     2         1.0       0.0

[244 rows x 8 columns]

In [ ]:
# Task
import pandas as pd
import seaborn as sns
df = sns.load_dataset("diamonds")
print(df.head(5))
print(df.shape)
print(df.columns)

   carat      cut color clarity  depth  table  price     x     y     z
0   0.23    Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
1   0.21  Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
2   0.23     Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31
3   0.29  Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
4   0.31     Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75
(53940, 10)
Index(['carat', 'cut', 'color', 'clarity', 'depth', 'table', 'price', 'x', 'y',
       'z'],
      dtype='object')

In [ ]:
cut_data = df[["cut"]]
encoder = OneHotEncoder(sparse_output = False)
encoded = encoder.fit_transform(cut_data)
print(encoded)

[[0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0.]
 ...
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0.]]

In [ ]:
print(encoder.get_feature_names_out())

['cut_Fair' 'cut_Good' 'cut_Ideal' 'cut_Premium' 'cut_Very Good']

In [ ]:
df

       carat        cut color clarity  depth  table  price     x     y     z
0       0.23      Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
1       0.21    Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
2       0.23       Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31
3       0.29    Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
4       0.31       Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75
...      ...        ...   ...     ...    ...    ...    ...   ...   ...   ...
53935   0.72      Ideal     D     SI1   60.8   57.0   2757  5.75  5.76  3.50
53936   0.72       Good     D     SI1   63.1   55.0   2757  5.69  5.75  3.61
53937   0.70  Very Good     D     SI1   62.8   60.0   2757  5.66  5.68  3.56
53938   0.86    Premium     H     SI2   61.0   58.0   2757  6.15  6.12  3.74
53939   0.75      Ideal     D     SI2   62.2   55.0   2757  5.83  5.87  3.64

[53940 rows x 10 columns]

In [ ]:
encoded_df = pd.DataFrame(
    encoded,
    columns = encoder.get_feature_names_out()
)
encoded_df

       cut_Fair  cut_Good  cut_Ideal  cut_Premium  cut_Very Good
0           0.0       0.0        1.0          0.0            0.0
1           0.0       0.0        0.0          1.0            0.0
2           0.0       1.0        0.0          0.0            0.0
3           0.0       0.0        0.0          1.0            0.0
4           0.0       1.0        0.0          0.0            0.0
...         ...       ...        ...          ...            ...
53935       0.0       0.0        1.0          0.0            0.0
53936       0.0       1.0        0.0          0.0            0.0
53937       0.0       0.0        0.0          0.0            1.0
53938       0.0       0.0        0.0          1.0            0.0
53939       0.0       0.0        1.0          0.0            0.0

[53940 rows x 5 columns]

In [ ]:
d = df.drop("cut", axis = 1)
final_df = pd.concat([d,encoded_df], axis = 1)
final_df
display(final_df.head(5))

,carat,color,clarity,depth,table,price,x,y,z,color_D,color_E,color_F,color_G,color_H,color_I,color_J
0,0.23,E,SI2,61.5,55.0,326,3.95,3.98,2.43,0.0,1.0,0.0,0.0,0.0,0.0,0.0
1,0.21,E,SI1,59.8,61.0,326,3.89,3.84,2.31,0.0,1.0,0.0,0.0,0.0,0.0,0.0
2,0.23,E,VS1,56.9,65.0,327,4.05,4.07,2.31,0.0,1.0,0.0,0.0,0.0,0.0,0.0
3,0.29,I,VS2,62.4,58.0,334,4.20,4.23,2.63,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4,0.31,J,SI2,63.3,58.0,335,4.34,4.35,2.75,0.0,0.0,0.0,0.0,0.0,0.0,1.0

In [ ]:
color_data = df[["color"]]
encoder = OneHotEncoder(sparse_output = False)
encoded = encoder.fit_transform(color_data)
print(encoded)

[[0. 1. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 ...
 [1. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 1. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]]

In [ ]:
print(encoder.get_feature_names_out())

['color_D' 'color_E' 'color_F' 'color_G' 'color_H' 'color_I' 'color_J']

In [ ]:
encoded_df = pd.DataFrame(
    encoded,
    columns = encoder.get_feature_names_out()
)
encoded_df

       color_D  color_E  color_F  color_G  color_H  color_I  color_J
0          0.0      1.0      0.0      0.0      0.0      0.0      0.0
1          0.0      1.0      0.0      0.0      0.0      0.0      0.0
2          0.0      1.0      0.0      0.0      0.0      0.0      0.0
3          0.0      0.0      0.0      0.0      0.0      1.0      0.0
4          0.0      0.0      0.0      0.0      0.0      0.0      1.0
...        ...      ...      ...      ...      ...      ...      ...
53935      1.0      0.0      0.0      0.0      0.0      0.0      0.0
53936      1.0      0.0      0.0      0.0      0.0      0.0      0.0
53937      1.0      0.0      0.0      0.0      0.0      0.0      0.0
53938      0.0      0.0      0.0      0.0      1.0      0.0      0.0
53939      1.0      0.0      0.0      0.0      0.0      0.0      0.0

[53940 rows x 7 columns]

In [ ]:
d = df.drop("color", axis = 1)
final_df = pd.concat([d,encoded_df], axis = 1)
final_df
display(final_df.head(5))

,carat,cut,clarity,depth,table,price,x,y,z,color_D,color_E,color_F,color_G,color_H,color_I,color_J
0,0.23,Ideal,SI2,61.5,55.0,326,3.95,3.98,2.43,0.0,1.0,0.0,0.0,0.0,0.0,0.0
1,0.21,Premium,SI1,59.8,61.0,326,3.89,3.84,2.31,0.0,1.0,0.0,0.0,0.0,0.0,0.0
2,0.23,Good,VS1,56.9,65.0,327,4.05,4.07,2.31,0.0,1.0,0.0,0.0,0.0,0.0,0.0
3,0.29,Premium,VS2,62.4,58.0,334,4.20,4.23,2.63,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4,0.31,Good,SI2,63.3,58.0,335,4.34,4.35,2.75,0.0,0.0,0.0,0.0,0.0,0.0,1.0

In [ ]:
from sklearn.preprocessing import OneHotEncoder
import pandas as pd
cut_data = df[["cut"]]
encoder_cut = OneHotEncoder(sparse_output=False)
encoded_cut = encoder_cut.fit_transform(cut_data)
encoded_df_cut = pd.DataFrame(encoded_cut, columns=encoder_cut.get_feature_names_out())
color_data = df[["color"]]
encoder_color = OneHotEncoder(sparse_output=False)
encoded_color = encoder_color.fit_transform(color_data)
encoded_df_color = pd.DataFrame(encoded_color, columns=encoder_color.get_feature_names_out())
clarity_data = df[["clarity"]]
encoder_clarity = OneHotEncoder(sparse_output=False)
encoded_clarity = encoder_clarity.fit_transform(clarity_data)
encoded_df_clarity = pd.DataFrame(encoded_clarity, columns=encoder_clarity.get_feature_names_out())
df_processed = df.drop(columns=["cut", "color", "clarity"])
final_df = pd.concat([df_processed, encoded_df_cut, encoded_df_color, encoded_df_clarity], axis=1)
display(final_df.head(5))

,carat,depth,table,price,x,y,z,cut_Fair,cut_Good,cut_Ideal,...,color_I,color_J,clarity_I1,clarity_IF,clarity_SI1,clarity_SI2,clarity_VS1,clarity_VS2,clarity_VVS1,clarity_VVS2
0,0.23,61.5,55.0,326,3.95,3.98,2.43,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
1,0.21,59.8,61.0,326,3.89,3.84,2.31,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
2,0.23,56.9,65.0,327,4.05,4.07,2.31,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
3,0.29,62.4,58.0,334,4.20,4.23,2.63,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
4,0.31,63.3,58.0,335,4.34,4.35,2.75,0.0,1.0,0.0,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0