<a href="https://colab.research.google.com/github/lakkireddylahari-bot/data-science-learning/blob/main/mergeipynb_(1)_ds.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#merge
# in real world  data analysis data is usually stored in multiple tablles
# ex:
# studnet deatils in one table
# student marks in another table
# so to combine these tables we will use merge
# pd.merge(
#     dataset1,
#     dataset2,
#     on =column name
#     how = type
# )

In [ ]:
import pandas as pd

In [ ]:
student_df = pd.read_csv("/content/drive/MyDrive/datsetsfordatasciencebytexl/students.csv")
print(student_df)

   student_id    name department        city
0         101    Ravi        CSE   Hyderabad
1         102   Priya        ECE  Vijayawada
2         103   Kiran        CSE      Guntur
3         104   Sneha        EEE     Chennai
4         105   Arjun       MECH   Bangalore
5         106   Meena      CIVIL   Hyderabad
6         107   Rahul        CSE       Vizag
7         108   Divya        ECE      Guntur
8         109  Vikram        EEE     Chennai
9         110  Anitha       MECH   Bangalore

In [ ]:
marks_df = pd.read_csv("/content/drive/MyDrive/datsetsfordatasciencebytexl/marks.csv")
print(marks_df)

   student_id  python  sql  machine_learning
0         101      85   80                75
1         102      90   85                88
2         103      78   70                72
3         105      88   92                85
4         106      76   75                70
5         107      95   90                96
6         111      67   60                65
7         112      72   68                66
8         109      81   79                77
9         110      89   91                90

In [ ]:
# inner merge
# it will takes only common data from both tables
result = pd.merge(
    student_df ,
    marks_df,
    on = 'student_id',
    how = 'inner'
)
print(result)

In [ ]:
#left merge
# allow rows from left dataframe

In [ ]:
student_df

   student_id    name department        city
0         101    Ravi        CSE   Hyderabad
1         102   Priya        ECE  Vijayawada
2         103   Kiran        CSE      Guntur
3         104   Sneha        EEE     Chennai
4         105   Arjun       MECH   Bangalore
5         106   Meena      CIVIL   Hyderabad
6         107   Rahul        CSE       Vizag
7         108   Divya        ECE      Guntur
8         109  Vikram        EEE     Chennai
9         110  Anitha       MECH   Bangalore

In [ ]:
marks_df

   student_id  python  sql  machine_learning
0         101      85   80                75
1         102      90   85                88
2         103      78   70                72
3         105      88   92                85
4         106      76   75                70
5         107      95   90                96
6         111      67   60                65
7         112      72   68                66
8         109      81   79                77
9         110      89   91                90

In [ ]:
result_l = pd.merge(
    student_df,
    marks_df,
    on ='student_id',
    how ='left'

)
print(result_l)

In [ ]:
result_l = pd.merge(
    student_df,
    marks_df,
    on ='student_id',
    how ='right'

)
print(result_l)

In [ ]:
result_l = pd.merge(
    student_df,
    marks_df,
    on ='student_id',
    how ='outer'

)
print(result_l)